---
- name: Install Knative Eventing
  hosts: localhost
  vars:
    knative_version: v0.25.0
  collections:
    - community.kubernetes
  tasks:
    - name: Install Knative Eventing CRDS
      command: |
        kubectl apply -f https://github.com/knative/eventing/releases/download/"{{ knative_version }}"/eventing-crds.yaml

    - name: Install Knative Eventing Core
      command: |
        kubectl apply -f https://github.com/knative/eventing/releases/download/"{{ knative_version }}"/eventing-core.yaml