---
- name: Install Knative Eventing
  hosts: localhost
  collections:
    - community.kubernetes
  tasks:
    - name: Install Knative Eventing CRDS
      command: |
        kubectl apply -f https://github.com/knative/eventing/releases/download/v0.25.0/eventing-crds.yaml

    - name: Install Knative Eventing Core
      command: |
        kubectl apply -f https://github.com/knative/eventing/releases/download/v0.25.0/eventing-core.yaml