---
- name: Uninstall Knative Serving
  hosts: localhost
  vars:
    knative_version: "{{ lookup('ini', 'version section=knative file=version.ini') }}"

  tasks:
    - name: Uninstall Knative Kourier
      command: |
        kubectl delete --ignore-not-found=true -f https://github.com/knative/net-kourier/releases/download/"{{ knative_version }}"/kourier.yaml

    - name: Patch CRDS ingresses.networking.internal.knative.dev to force deletion
      command: |
        kubectl patch crd/ingresses.networking.internal.knative.dev -p '{"metadata":{"finalizers":[]}}' --type=merge

    - name: Uninstall Knative Serving CRDS
      command: |
        kubectl delete --ignore-not-found=true -f https://github.com/knative/serving/releases/download/"{{ knative_version }}"/serving-crds.yaml

    - name: Uninstall Knative Serving Core
      command: |
        kubectl delete --ignore-not-found=true -f https://github.com/knative/serving/releases/download/"{{ knative_version }}"/serving-core.yaml